install:
 - source ./support/texlive.sh

cache:
  directories:
    - /tmp/texlive
    - $HOME/.texlive

script:
 - texlua l3build.lua ctan -H --show-log-on-error

notifications:
  email:
    recipients:
      - latex3-commits@tug.org
    on_success: change
    on_failure: always
    on_start:   never

deploy:
  - provider: releases
    api_key:
      secure: BJ4PXlX4H94+h+ucQM4+3eTy7o0kJPs+piH0p30UdQrf82rNGXJPOq8U38bmh/9O2BwvMjn/2qOPkpQBJ29XNMWbqQMO66EwCbNke4340p4otQn5k+adfOdBA20bRu1lrkn1FbPf/nVtGZXEJXcRBRnONMNicIO02tDIW6JqFrPMEyNGgnFApO3p2rqHIOjwNSWrxiBS8ab1MP+u4hzKSSzk1LUa1qGPxYPMtKWxAJfFyEKxaiVNIpvULncf9VemPSoBVCpm0qk9GUhEDIVNmiD8KnB4bBPzc3MraPJBgah/zdwR8NdXQ9gp9ZrWmT5zZxFHXtoX6r64R3Uy/YYJqjZK1oDAfz4ksGdmyos3v1lIsFniWI7ez/z4N87jLuS2bZ00dDCPeoN5OVkOmOY0STXc9+Dg59nGiinePoevhft1+Yso5oHTKlzgiJmNsur+0ovri3a0LBD8+6LfXvCH3lktpigBHuKSN/cRFVNyb2KfuncgyZ9zUhOfNNZcYtbxHr+uRZo+h5AwRwctvTdBJD+96j2Woas6kThz9et8jgRwwII5P/qQfV+aIxOWfP7rMnKrfbqMtM2tCh9wPqfgNEIG6ZClHvG2ixsHoL04wIEBuTwkMLMDAeyaBS3XILxjhsXV2+CJd09pFc9N2q21zLfEaZGeh9A837e8AjWJtuM=
    file_glob: true
    file:
      - build/distrib/ctan/*.zip
    skip_cleanup: true
    on:
      tags: true
      branch: master
    prerelease: false
    draft: true
